defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: grad_norm
  - _self_
scheduler:
  decay_rate: 0.95
  decay_steps: 10000
optimizer:
  lr: 5e-4
training:
  rec_validation_freq: 10000
  rec_inference_freq: 10000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 100000
  amp: True
batch_size:
  Inlet: 300
  Outlet: 300
  NoSlip: 10000
  Symmetry: 3000
  Interior: 3000
  MCIP: 1000
custom:
  nd:
    length: # 特征长度 除了改这边以外还需要修改geometry里面的设置
      value: 300
      unit: um
    velocity: # 特征速度
      value: 1
      unit: m/s
    pressure: # 特征压强
      value: 10000
      unit: kg/(m*s^2)
  ns:
    nu: # 运动粘度
      value: 0.000001
      unit: m^2/s
    rho: # 密度
      value: 1000
      unit: kg/(m^3)
  bc:
    inlet_vol_flow: # 入口流量
      value: 2
      unit: ul/s
  batch_per_epoch: 1000
run_mode: "train"
network_dir: "./"
initialization_network_dir: ""
cuda_graphs: True